feat: removed indiscriminate * imports for explicit ones
KILTprotocol/demo-client pull request #304
Opened 2020-12-09 12:50 UTC by LeonFLK

## fixes KILTProtocol/ticket#312

Has no logic changes, just removes indiscriminate `* as sdk` imports in favor for explicit ones that are needed.

## Checklist:

- [ ] I have verified that the code works
- [ ] I have verified that the code is easy to understand
  - [ ] If not, I have left a well-balanced amount of inline comments
- [ ] I have [left the code in a better state](https://deviq.com/boy-scout-rule/)
- [ ] I have documented the changes (where applicable)

2020-12-16 11:19 UTC, rflechtner requested changes
Just a typo, but it doesn't build like this. LG otherwise

2020-12-16 18:31 UTC, LeonFLK commented on src/components/SelectAttestedClaim/SelectAttestedClaim.tsx
> +  cTypeHash?: SDKICTypeu['hash']
```suggestion
  cTypeHash?: SDKICType['hash']
```

2020-12-16 18:35 UTC, LeonFLK commented on src/components/SelectAttestedClaim/SelectAttestedClaim.tsx
> +  cTypeHash?: SDKICTypeu['hash']
WEEOO-WEEEOO
Danke, aber da hättest du auch ne suggestion commiten können.

2020-12-16 18:35 UTC, merged

2020-12-17 09:29 UTC, rflechtner commented on src/components/SelectAttestedClaim/SelectAttestedClaim.tsx
> +  cTypeHash?: SDKICTypeu['hash']
das wär ja langweilig!